openapi: 3.0.0
info:
  title: Topelectro API
  description: Here goes description
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://production-example:8000/api
    description: production server

paths:
  # /login:
  # $ref: "./_swagger/paths/auth.yaml#/paths/~1login"
  # /user:
  # $ref: "./_swagger/paths/auth.yaml#/paths/~1user"

  /products:
    $ref: "./_swagger/paths/products.yaml#/paths/~1products"
  /products/{id}:
    $ref: "./_swagger/paths/products.yaml#/paths/~1products~1{id}"

  # /categories:
  # $ref: "./_swagger/paths/categories.yaml#/paths/~1categories"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      allOf:
        - $ref: "./_swagger/schemas/user.yaml#/components/schemas/User"
    Product:
      allOf:
        - $ref: "./_swagger/schemas/product.yaml#/components/schemas/Product"
    Category:
      allOf:
        - $ref: "./_swagger/schemas/category.yaml#/components/schemas/Category"
